### PR TITLE
Fix bug when order amound has more than 2 digits

### PR DESCRIPTION
**Pull request by Echron**
MultiSafepay API only accepts integers, no numbers

### CODE REVIEW

**Comment by JonkRuud** [comment]
Hello Echron,

Do yo mind changing the request to our develop branch instead? Thanks for noticing this issue and creating a solution.

**Comment by Echron** [comment]
Good morning,

of course. I requested it for the master branch because it's a hotfix and i didn't know how much changes you would do on the develop branch before making a new version.

I'll change it

**Comment by JonkRuud** [comment]
@Echron I noticed it was still for the master branch, so I added it now to the develop branch. I will close this one as its now added.

**Comment by Echron** [comment]
Yea i didn't have time to change it, thx

**Pull request closed without merging**
