### PR TITLE
Progressive web app

### PR DESCRIPTION
**Pull request by Hexmage**
We have been working with this version on live for a while. But seeing as it is now behind the master branch of the module. Could this be merged into the master branch?

### CODE REVIEW

**Comment by Jasper-MultiSafepay** [comment]
I have added this request to our upcoming sprint to merge this branch and include PWA into our master branch.
JIRA: PLGMAGTWOS-611
I will notify here when it is merged.

**Comment by Jasper-MultiSafepay** [comment]
@Hexmage @dheesbeen 
We have been working at merging this but are encountering the following issue:
When placing an order through the normal frontend/checkout, the order observer is called, which we do not want to happen as it starts another transaction.

**Cause**
Order placement within Magento is done through the REST API, even when you are on the frontend.
Within this PR we have added sales_order_place_after to etc/webapi_rest/events.xml, leading to this issue.

*Possible solutions*
- We remove the order observer from etc/webapi_rest/events.xml, but this could break your integrations, unless you are only using etc/graphql/events.xml
- We can add a button within the plugin settings, to enable/disable PWA. When disabled, we disable the order observer for webapi_rest
- We move this code into a separate plugin and make it depends on Magento2Msp

I would go for the first solution, but that depends on your feedback.
If you have other ideas/suggestions I would like to hear it as well.
Until then I will put this PR on hold.

**Comment by Hexmage** [comment]
@Jasper-MultiSafepay 
We currently only have 1 shop running the rest integration. All future implementations will not use this. So I'd say go for the first solution, and I'll manually update any issues with for the 1 shop.

**Comment by Hexmage** [comment]
@Jasper-MultiSafepay 
Any timeline on when this will be merged.

**Comment by vinodsowdagar** [comment]
@Hexmage 

We have implemented the progressive-web-app changes into our new release: https://github.com/MultiSafepay/Magento2Msp/releases/tag/1.12.0

For now i will close this pull request, since the changes are already merged.
If you have any questions or feedback, please feel free to create a new issue or contact our integration team.

**Pull request closed without merging**
