### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JonkRuud**

### CODE REVIEW

**Comment by hostep** [comment]
@JonkRuud: a lot of file's file permissions have changed from 0644 to 0755 due to this PR.
Can you make sure all files have permissions 0644? Php files and image files shouldn't have the executable bit enabled.

```bash
# list files with incorrect permissions
find . -type f ! -perm 0644

# fix them
find . -type f ! -perm 0644 -print0 | xargs -0 chmod 0644
```

Tnx! :)

**Comment by JonkRuud** [comment]
@hostep Thanks for reporting, we will look into this one and correct this.

**Comment by JonkRuud** [comment]
@hostep File permission should now be okay again within the develop branch.

**Comment by hostep** [comment]
Nice, thanks! :)

**Pull request merged**
