### PR TITLE
Dispatch event before Transaction Request is sent

### PR DESCRIPTION
**Pull request by duckchip**
Hi guys,

This is a PR for [an issue](https://github.com/MultiSafepay/Magento2Msp/issues/8) that hasn't been fixed.

It basically dispatches an event that adds the array in an object in order to manipulate the data. 

This way we can change i.e. the description 

It would be really nice if this can be added to the core :) 

Thx in advance!

### CODE REVIEW

**Comment by Jasper-MultiSafepay** [comment]
Thanks @duckchip for your contribution.
It looks correctly based on the reported issue, so we will add it for review in our current sprint

**Comment by Jasper-MultiSafepay** [comment]
@duckchip 
We rebased onto our develop branch and resolved the merge conflict.
This has now been merged and will be coming in the next release.
Thank you for contributing and we will credit the author on our changelog 👍 
We will close this PR and close the issue when we release.

**Comment by hostep** [comment]
Hi @Jasper-MultiSafepay 

Can you let us know when this feature will be released?
I can't seem to find it in version 1.8.0, or am I missing something?

Thanks!

**Comment by vinodsowdagar** [comment]
@hostep

I checked and it is located in our develop branch, see d1d2637

It just missed the cutoff for 1.8.0.
It will be included in the next release, which is scheduled for the end of this month.

**Comment by hostep** [comment]
@Vinod-MultiSafepay: just to confirm: a new version with this change, is still scheduled for this week? If not: can you let us know a rough estimate? We are kind of waiting on this for at least 2 projects now. Thanks! 🙂

**Comment by vinodsowdagar** [comment]
Hi @hostep  ,

We have created a release candidate for version 1.9.0 of our extension. 
Please keep in mind that this version is not yet an official release. 
We will give you an update when the official release will be ready.

It is already possible to use this version of the extension. 
The extension can be installed by using the following command:

`composer require multisafepay/magento2msp:dev-release/1.9.0-RC1`

We recommend first testing the extension on a staging or testing environment, before using this in production.

Please let us know if you have any further questions or comments.

**Comment by hostep** [comment]
Hi @Vinod-MultiSafepay 

I can confirm this feature works as expected and we can now very easily manipulate data which is send to MultiSafepay, which is awesome, thanks for that!

Do you already know when a stable version of 1.9 is to be released?
I would prefer to deploy a stable version to this particular shop then a Release Candidate.

Our goal would be to do the last bit of testing next week and go live in the week of the 24th of February.
Will a new stable version be released by somewhere next week? That would be appreciated!

Thanks!

**Comment by vinodsowdagar** [comment]
Hi @hostep ,

We are glad that you were able to implement the feature as intended. 

Unfortunately we could not make the requested release date of 24 February, but we were able to release the stable version as of now:

https://github.com/MultiSafepay/Magento2Msp/tree/1.9.0

I hope to have informed you sufficiently. 
If you have any further questions, do let us know.

**Comment by hostep** [comment]
Ok thanks for the reply @Vinod-MultiSafepay!

It looks like nothing significant was changed [between 1.9.0-RC1 and 1.9.0](https://github.com/MultiSafepay/Magento2Msp/compare/release/1.9.0-RC1...1.9.0)
So we should be able to switch to it without having to re-test everything.

The one thing I'm worried about is the version `1.9.0-RC1` in the `setup_version` of the `module.xml` file, I'm not sure if Magento will be able to handle that and see `1.9.0` as a new version, but let's hope it will :)

**Comment by hostep** [comment]
Ok, looks like Magento can work with that `1.9.0-RC1` version in the `setup_module` database table, it got changed to `1.9.0` after upgrading to the stable version, nice!

All is good now, thanks! :)

**Pull request closed without merging**
